name: haddock

on: push

jobs:
  runHaddock:
    name: run haddock generation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: prepare haddock generation
        run: git worktree add haddock
      - uses: Cj-bc/generate-haddock-action@v0.1.2
      - name: commit generated document
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          cd haddock
          git add *
          git commit -m "CI: new haddock build"
          git push origin haddock

        
          
      
